### ISSUE TITLE
P0196: none and Nullable types - The section on nesting is unclear

### ISSUE THREAD

**Issue by tituswinters** [viboes/std-make#4]
The section on nesting is unclear.  

One of the benefits of the original notion of having none_t<T> was that it could be used where necessary to disambiguate cases like:
`optional<any> oa = none;`
via
`optional<any> oa = none_t<any>{};`
vs.
`optional<any> oa = {};`

**Comment by viboes** [comment]
I believe that we don't need to support this case as any is already **Nullable**. 

IMO this is equivalent to nesting smart pointers 

```
 unique_ptr<unique_ptr<int>> uui = nullptr;
```

**Comment by tituswinters** [comment]
Is the intent to demonstrate that there is no need to do anything special for any nested nullable types?

**Comment by viboes** [comment]
Yes and not.

I wanted to reduce the scope of the proposal and provide the same kind of interface for _Nullable_ than for as _NullablePointer_ (`none` versus `nullptr`).

The paper includes an alternative design with lift that could respond to the need.

``` c++
 optional<any> oa = lift(none);
```

This works when there is enough context (no ambiguity) and the optional class adds a conversion from `lifted<U>`. Does this respond to your needs or do you need the general case to disambiguate?

If you need the general case for _Nullable_,  you would need it also for _NullablePointer_ types, isn't it?
I plan to provide the case explicit case for _Nullable_ and _NullablePointer_ types with a function `no_value`, but this will be part of the **C++ generic factories** paper. `no_value` would be a function because it accepts class templates (optional) and classes (any).

``` c++
optional<int> oan = no_value<optional>(); //
any an = no_value<any>(); 
unique_ptr<any> upn = no_value<unique_ptr>(); 

optional<any> oav = no_value<any>(); 
unique_ptr<optional<int>> oav = no_value<optional>(); 
unique_ptr<any> oav = no_value<any>(); 
```

This requires however some specific conversion from the result of no_value<T>() to optional, any, unique_ptr, ...

**Comment by tituswinters** [comment]
I think the "lift" design (placed where it is in the paper) is confusing.  Perhaps if you shift it to the end of the paper as an appendix "Alternate designs" that might help.

**Comment by viboes** [comment]
Agreed. I planed to do it.

**Comment by viboes** [comment]
lift was removed.
